### ISSUE TITLE
Db folder write issues 

### ISSUE THREAD

**Issue by compactly8274** [JPDVM2014/kapowarr#1]
Installing from this in community apps or the official repository following the compose steps it will error out and stop. 

The PUID and PGID are set as 1000 for each but changing them to the standard 99/100 respectively doesn’t help. The python script never writes anything to the db folder location, whether it’s the community app default or moving it into appdata. 

The way I got it to run was to create a volume in portainer and attach the db folder location to that instead of binding location, but I’d like to have unraid community app native updates if possible

**Comment by JPDVM2014** [comment]
It never creates the .db file? If not, I'd say try manually making the kapowarr.db file, and see if that helps. It may be a permission issue. Also see if there is any info in the logs.

If it makes the db, but just never writes to it, you may have to open an issue on the main project, https://github.com/Casvt/Kapowarr. All I did for the CA template was use the docker compose instructions from there.

**Comment by compactly8274** [comment]
I tried creating the file and then it couldn't write to it, even after matching permissions to the PUID and PGID set in Portainer (99/100).

What got it going was to set the PUID and PGID as variables in the update container window, then set them to 99/100 respectively. This allowed the container to write to the appdata location, even though doing the same thing in portainer didn't.

If you update the template to include those two variables (could even be hidden settings) that should fix it for anyone else that deploys this container.

**Comment by JPDVM2014** [comment]
Thanks for reporting back. I added PUID and PGID as variables in the template. It should update in the CA store soon.

**Comment by JPDVM2014** [comment]
Thanks for reporting back. I added PUID and PGID as variables in the template. It should update in the CA store soon.

**Comment by JPDVM2014** [comment]
Thanks for reporting back. I added PUID and PGID as variables in the template. It should update in the CA store soon.
